import { Platform, StyleSheet } from 'react-native';

import { getAvColors } from '@/constants/themed-palettes';

/** @param {import('@/constants/themes').AppThemeColors} c */
export function createAvailabilityStyles(c) {
  const AvColors = getAvColors(c);
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: AvColors.bg },
  scroll: { paddingHorizontal: 16, paddingBottom: 120, paddingTop: 8 },
  boardHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: AvColors.blue,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  boardHeroIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boardHeroTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '800',
    color: c.heroText,
    letterSpacing: -0.3,
  },
  card: {
    backgroundColor: AvColors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: AvColors.dividerSoft,
    padding: 16,
    marginBottom: 14,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  filtersHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  filtersTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: AvColors.text,
  },
  filtersSub: {
    fontSize: 13,
    color: AvColors.textMuted,
    marginBottom: 14,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  filterField: {
    flex: 1,
    minWidth: 0,
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: AvColors.textMuted,
    marginBottom: 6,
  },
  filterInput: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: AvColors.inputBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AvColors.inputBorder,
    paddingHorizontal: 12,
    paddingVertical: 11,
    minHeight: 44,
  },
  filterInputText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  filterPlaceholder: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: AvColors.inputPlaceholder,
  },
  dropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: 4,
    backgroundColor: AvColors.dropdownBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AvColors.border,
    zIndex: 40,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: AvColors.divider,
  },
  dropdownItemText: {
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  pillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: AvColors.inputBorder,
    backgroundColor: AvColors.chipBg,
  },
  pillActive: {
    backgroundColor: AvColors.chipActiveBg,
    borderColor: AvColors.chipActiveBorder,
  },
  pillText: {
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  pillTextActive: {
    color: AvColors.chipActiveText,
    fontWeight: '700',
  },
  pillDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: AvColors.inputBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AvColors.inputBorder,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: AvColors.text,
    paddingVertical: 10,
  },
  peopleHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  peopleTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: AvColors.text,
  },
  peopleCount: {
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.textMuted,
  },
  personCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AvColors.dividerSoft,
    backgroundColor: AvColors.surfaceElevated,
    marginBottom: 10,
  },
  personMain: {
    flex: 1,
    minWidth: 0,
  },
  personName: {
    fontSize: 16,
    fontWeight: '800',
    color: AvColors.text,
  },
  personRoleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  personRole: {
    fontSize: 12,
    fontWeight: '500',
    color: AvColors.textMuted,
  },
  personGdc: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    color: AvColors.blue,
  },
  personRight: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minWidth: 88,
  },
  statusBadge: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusBadgePresent: {
    backgroundColor: AvColors.greenBg,
  },
  statusBadgeAbsent: {
    backgroundColor: AvColors.orangeBg,
  },
  statusBadgeLeave: {
    backgroundColor: AvColors.redBg,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusBadgeTextPresent: { color: AvColors.greenText },
  statusBadgeTextAbsent: { color: AvColors.orangeText },
  statusBadgeTextLeave: { color: AvColors.orangeText },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  activityDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  activityText: {
    fontSize: 11,
    fontWeight: '600',
    color: AvColors.textMuted,
  },
  emptyBox: {
    paddingVertical: 28,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: AvColors.textMuted,
    fontWeight: '500',
  },
  squareAvatar: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: AvColors.avatarBg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  squareAvatarImage: {
    width: 56,
    height: 56,
    borderRadius: 12,
  },
  squareAvatarText: {
    fontSize: 20,
    fontWeight: '800',
    color: AvColors.blue,
  },
  errorBanner: {
    marginBottom: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: AvColors.redBg,
    borderWidth: 1,
    borderColor: AvColors.red,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  errorBannerText: { flex: 1, fontSize: 13, color: AvColors.orangeText, fontWeight: '600' },
  errorBannerBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: AvColors.red,
  },
  errorBannerBtnText: { color: '#fff', fontSize: 12, fontWeight: '800' },
});
}
