import { Platform, StyleSheet } from 'react-native';

export const AvColors = {
  blue: '#2563EB',
  green: '#16A34A',
  greenBg: '#DCFCE7',
  greenText: '#15803D',
  red: '#DC2626',
  redBg: '#FEE2E2',
  orange: '#EA580C',
  orangeBg: '#FFEDD5',
  orangeText: '#C2410C',
  purple: '#7C3AED',
  border: '#E5E7EB',
  bg: '#F1F5F9',
  card: '#FFFFFF',
  text: '#0F172A',
  textMuted: '#64748B',
  white: '#FFFFFF',
};

export const availabilityStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: AvColors.bg },
  scroll: { paddingHorizontal: 16, paddingBottom: 120, paddingTop: 8 },
  boardHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: AvColors.blue,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  boardHeroIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boardHeroTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '800',
    color: AvColors.white,
    letterSpacing: -0.3,
  },
  card: {
    backgroundColor: AvColors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8EDF3',
    padding: 16,
    marginBottom: 14,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  filtersHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  filtersTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: AvColors.text,
  },
  filtersSub: {
    fontSize: 13,
    color: AvColors.textMuted,
    marginBottom: 14,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  filterField: {
    flex: 1,
    minWidth: 0,
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: AvColors.textMuted,
    marginBottom: 6,
  },
  filterInput: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 12,
    paddingVertical: 11,
    minHeight: 44,
  },
  filterInputText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  filterPlaceholder: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: '#94A3B8',
  },
  dropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: 4,
    backgroundColor: AvColors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AvColors.border,
    zIndex: 40,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  dropdownItemText: {
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  pillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: AvColors.white,
  },
  pillActive: {
    backgroundColor: '#EFF6FF',
    borderColor: '#BFDBFE',
  },
  pillText: {
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  pillTextActive: {
    color: AvColors.blue,
    fontWeight: '700',
  },
  pillDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: AvColors.text,
    paddingVertical: 10,
  },
  peopleHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  peopleTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: AvColors.text,
  },
  peopleCount: {
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.textMuted,
  },
  personCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E8EDF3',
    backgroundColor: AvColors.white,
    marginBottom: 10,
  },
  personMain: {
    flex: 1,
    minWidth: 0,
  },
  personName: {
    fontSize: 16,
    fontWeight: '800',
    color: AvColors.text,
  },
  personRoleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  personRole: {
    fontSize: 12,
    fontWeight: '500',
    color: AvColors.textMuted,
  },
  personGdc: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    color: AvColors.blue,
  },
  personRight: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minWidth: 88,
  },
  statusBadge: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusBadgePresent: {
    backgroundColor: AvColors.greenBg,
  },
  statusBadgeAbsent: {
    backgroundColor: AvColors.orangeBg,
  },
  statusBadgeLeave: {
    backgroundColor: '#FFE4E6',
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusBadgeTextPresent: { color: AvColors.greenText },
  statusBadgeTextAbsent: { color: AvColors.orangeText },
  statusBadgeTextLeave: { color: '#BE123C' },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  activityDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  activityText: {
    fontSize: 11,
    fontWeight: '600',
    color: AvColors.textMuted,
  },
  emptyBox: {
    paddingVertical: 28,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: AvColors.textMuted,
    fontWeight: '500',
  },
  squareAvatar: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  squareAvatarImage: {
    width: 56,
    height: 56,
    borderRadius: 12,
  },
  squareAvatarText: {
    fontSize: 20,
    fontWeight: '800',
    color: AvColors.blue,
  },
});
