import { Platform, StyleSheet } from 'react-native';

import { getTsColors } from '@/constants/themed-palettes';
import { lightTheme } from '@/constants/themes';

/** @param {import('@/constants/themes').AppThemeColors} c */
export function createTimesheetStyles(c) {
  const TsColors = getTsColors(c);
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: TsColors.bg },
  scroll: { paddingHorizontal: 16, paddingBottom: 120, paddingTop: 4 },
  headerBlock: {
    marginBottom: 16,
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: TsColors.text,
    letterSpacing: -0.3,
    marginBottom: 14,
  },
  segmentedWrap: {
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: TsColors.white,
    borderRadius: 18,
    padding: 4,
    minHeight: 76,
  },
  segmentBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
    paddingBottom: 4,
    paddingHorizontal: 4,
    borderRadius: 14,
    backgroundColor: 'transparent',
  },
  segmentBtnPressed: {
    opacity: 0.92,
  },
  segmentBtnActive: {
    backgroundColor: TsColors.segmentActiveBg,
  },
  segmentBtnContent: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 2,
  },
  segmentText: {
    fontSize: 10,
    fontWeight: '500',
    color: TsColors.textMuted,
    textAlign: 'center',
    lineHeight: 13,
    letterSpacing: 0.05,
    maxWidth: '100%',
  },
  segmentTextActive: {
    color: TsColors.blue,
    fontWeight: '600',
  },
  segmentIndicator: {
    alignSelf: 'stretch',
    height: 3,
    marginTop: 8,
    marginHorizontal: 10,
    borderRadius: 2,
    backgroundColor: TsColors.blue,
  },
  segmentIndicatorSpacer: {
    height: 3,
    marginTop: 8,
    marginHorizontal: 10,
    backgroundColor: 'transparent',
  },
  dashboardHero: {
    backgroundColor: TsColors.blue,
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    ...Platform.select({
      ios: {
        shadowColor: '#1e3a8a',
        shadowOpacity: 0.2,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 4 },
    }),
  },
  dashboardHeroTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  dashboardDate: {
    fontSize: 15,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.95)',
  },
  dashboardCalBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  dashboardTile: {
    flexGrow: 1,
    flexBasis: '47%',
    minWidth: 140,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: TsColors.white,
    borderRadius: 12,
    padding: 12,
  },
  dashboardTileIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardTileText: {
    flex: 1,
    minWidth: 0,
  },
  dashboardTileLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: TsColors.textMuted,
  },
  dashboardTileValue: {
    marginTop: 2,
    fontSize: 22,
    fontWeight: '800',
    color: TsColors.text,
    letterSpacing: -0.5,
  },
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  statCard: {
    flexGrow: 1,
    flexBasis: '47%',
    minWidth: 150,
    backgroundColor: TsColors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: TsColors.border,
    padding: 14,
  },
  statLabel: { fontSize: 13, fontWeight: '600', color: TsColors.textMuted },
  statValue: { fontSize: 28, fontWeight: '800', color: TsColors.text, letterSpacing: -0.5 },
  filtersRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
    alignItems: 'center',
  },
  filterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: TsColors.white,
    borderWidth: 1,
    borderColor: TsColors.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 42,
  },
  filterPillText: { fontSize: 13, fontWeight: '600', color: TsColors.text },
  searchWrap: {
    flex: 1,
    flexBasis: 200,
    minWidth: 160,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: TsColors.white,
    borderWidth: 1,
    borderColor: TsColors.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 42,
  },
  searchInput: { flex: 1, fontSize: 13, color: TsColors.text, paddingVertical: 4 },
  roleMenu: {
    position: 'absolute',
    top: 46,
    left: 0,
    zIndex: 20,
    backgroundColor: TsColors.white,
    borderWidth: 1,
    borderColor: TsColors.border,
    borderRadius: 12,
    minWidth: 160,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOpacity: 0.12,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 6 },
    }),
  },
  roleMenuItem: { paddingHorizontal: 14, paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: TsColors.divider },
  roleMenuItemText: { fontSize: 13, fontWeight: '600', color: TsColors.text },
  dateMenu: {
    position: 'absolute',
    top: 46,
    left: 0,
    zIndex: 20,
    backgroundColor: TsColors.white,
    borderWidth: 1,
    borderColor: TsColors.border,
    borderRadius: 12,
    minWidth: 140,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOpacity: 0.12,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 6 },
    }),
  },
  employeeCard: {
    backgroundColor: TsColors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: TsColors.border,
    marginBottom: 10,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOpacity: 0.05,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
      },
      android: { elevation: 2 },
    }),
  },
  employeeHead: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: TsColors.avatarBg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    backgroundColor: TsColors.surfaceMuted,
  },
  avatarText: { fontSize: 14, fontWeight: '800', color: TsColors.blue },
  employeeMeta: { flex: 1, minWidth: 0 },
  employeeName: { fontSize: 15, fontWeight: '800', color: TsColors.text },
  employeeRole: { marginTop: 2, fontSize: 12, fontWeight: '500', color: TsColors.textMuted },
  employeeRight: { alignItems: 'flex-end', gap: 6 },
  employeeGdc: { fontSize: 11, fontWeight: '600', color: TsColors.textMuted },
  expandedBody: {
    borderTopWidth: 1,
    borderTopColor: TsColors.divider,
    paddingHorizontal: 12,
    paddingBottom: 14,
    paddingTop: 10,
  },
  timelineRow: { flexDirection: 'row', justifyContent: 'space-between' },
  timelineCol: { flex: 1, alignItems: 'center', gap: 4 },
  timelineDate: { fontSize: 11, fontWeight: '700', color: TsColors.text },
  timelineDay: { fontSize: 10, fontWeight: '500', color: TsColors.textMuted },
  statusDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  statusDotText: { fontSize: 12, fontWeight: '800', color: TsColors.white },
  summaryCountsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    gap: 12,
    paddingVertical: 8,
  },
  summaryCountItem: { alignItems: 'center' },
  summaryCountVal: { fontSize: 18, fontWeight: '800', color: TsColors.text },
  summaryCountLbl: { fontSize: 11, fontWeight: '600', color: TsColors.textMuted, marginTop: 2 },
  legendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: TsColors.divider,
  },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  legendDot: { width: 10, height: 10, borderRadius: 5 },
  legendText: { fontSize: 11, fontWeight: '600', color: TsColors.textMuted },
  emptyBox: {
    backgroundColor: TsColors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: TsColors.border,
    padding: 24,
    alignItems: 'center',
  },
  emptyText: { fontSize: 13, color: TsColors.textMuted, fontWeight: '600', textAlign: 'center' },
  banner: {
    backgroundColor: TsColors.exportBtnDangerBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: TsColors.red,
    padding: 12,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  bannerText: { flex: 1, fontSize: 12, color: TsColors.red, fontWeight: '600' },
  bannerBtn: {
    backgroundColor: TsColors.blue,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  bannerBtnText: { color: TsColors.white, fontSize: 12, fontWeight: '700' },
  recordCard: {
    backgroundColor: TsColors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: TsColors.border,
    padding: 14,
    marginBottom: 10,
  },
  recordTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  clockRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10 },
  clockPill: {
    flex: 1,
    backgroundColor: TsColors.timePanelBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: TsColors.border,
    padding: 10,
  },
  clockLbl: { fontSize: 10, fontWeight: '700', color: TsColors.blue },
  clockVal: { marginTop: 2, fontSize: 13, fontWeight: '800', color: TsColors.text },
  logScreenTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: TsColors.text,
    letterSpacing: -0.3,
    marginBottom: 14,
  },
  logFilterCard: {
    backgroundColor: TsColors.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: TsColors.dividerSoft,
    padding: 14,
    marginBottom: 14,
    gap: 12,
  },
  logFilterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  logFilterField: {
    flexGrow: 1,
    flexBasis: '46%',
    minWidth: 140,
  },
  logFilterFieldWide: {
    flexGrow: 1,
    flexBasis: '100%',
  },
  logFilterLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: TsColors.textMuted,
    marginBottom: 6,
  },
  logFilterInput: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: TsColors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: TsColors.inputBorder,
    paddingHorizontal: 12,
    paddingVertical: 11,
    minHeight: 44,
  },
  logFilterInputText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: TsColors.text,
  },
  logFilterInputPlaceholder: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: TsColors.inputPlaceholder,
  },
  logExportBar: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  logPdfBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: TsColors.infoBorder,
    backgroundColor: TsColors.exportBtnBg,
  },
  logPdfBtnSecondary: {
    borderColor: TsColors.red,
    backgroundColor: TsColors.exportBtnDangerBg,
  },
  logPdfBtnDisabled: {
    opacity: 0.6,
  },
  logPdfBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: TsColors.blue,
  },
  logSearchStatusRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
    width: '100%',
  },
  logSearchField: {
    minWidth: 0,
  },
  logSearchField70: {
    flex: 7,
    minWidth: 0,
  },
  logSearchFieldFull: {
    flex: 1,
    minWidth: 0,
  },
  logStatusField30: {
    flex: 3,
    minWidth: 0,
    maxWidth: 120,
  },
  logListHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: TsColors.blue,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  logListHeaderText: {
    fontSize: 13,
    fontWeight: '700',
    color: TsColors.white,
  },
  logListHeaderSub: {
    fontSize: 12,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.85)',
  },
  logRecordCard: {
    backgroundColor: TsColors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: TsColors.dividerSoft,
    padding: 14,
    marginBottom: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  logRecordTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  logRecordName: {
    fontSize: 17,
    fontWeight: '800',
    color: TsColors.text,
    letterSpacing: -0.2,
  },
  logRecordSub: {
    marginTop: 3,
    fontSize: 12,
    fontWeight: '500',
    color: TsColors.textMuted,
  },
  logRecordHeaderEnd: {
    alignItems: 'flex-end',
    gap: 6,
  },
  logDurationChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: TsColors.durationChipBg,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  logDurationChipAmber: {
    backgroundColor: TsColors.durationChipAmberBg,
  },
  logDurationChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: TsColors.blue,
  },
  logDurationChipTextAmber: {
    color: '#C2410C',
  },
  logStatusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  logStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  logStatusChipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  logMetaBar: {
    flexDirection: 'row',
    backgroundColor: TsColors.metaBarBg,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginBottom: 12,
    gap: 4,
  },
  logMetaBarManual: {
    backgroundColor: TsColors.metaBarManualBg,
  },
  logMetaTile: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 4,
    minWidth: 0,
  },
  logMetaTileLbl: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: '600',
    color: TsColors.textMuted,
    textAlign: 'center',
  },
  logMetaTileVal: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '700',
    color: TsColors.text,
    textAlign: 'center',
  },
  logInOutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logTimePanel: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: TsColors.timePanelBg,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: TsColors.timePanelBorder,
  },
  logTimePanelLbl: {
    fontSize: 10,
    fontWeight: '800',
    color: TsColors.blue,
    letterSpacing: 0.3,
  },
  logTimePanelVal: {
    marginTop: 3,
    fontSize: 16,
    fontWeight: '800',
    color: TsColors.text,
    letterSpacing: -0.3,
  },
  logStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  logStatusBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  logDropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: 4,
    backgroundColor: TsColors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: TsColors.border,
    zIndex: 40,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOpacity: 0.08,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 4 },
    }),
  },
});

}

export function statusDotStyle(code, ts = getTsColors(lightTheme)) {
  switch (String(code || '').toUpperCase()) {
    case 'P':
      return { bg: ts.green, label: 'P' };
    case 'A':
      return { bg: ts.red, label: 'A' };
    case 'LV':
      return { bg: ts.orange, label: 'L' };
    case 'LT':
      return { bg: ts.purple, label: 'L' };
    case 'H':
      return { bg: ts.blue, label: 'H' };
    case 'W':
      return { bg: '#9CA3AF', label: '-' };
    default:
      return { bg: '#CBD5E1', label: '-' };
  }
}
