import { Platform, StyleSheet } from 'react-native';

import { getAvColors } from '@/data/constants/themed-palettes';

/** @param {import('@/data/constants/themes').AppThemeColors} c */
export function createAvailabilityStyles(c) {
  const AvColors = getAvColors(c);
  const isDark = c.mode === 'dark';
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: AvColors.bg },
  scroll: { paddingHorizontal: 16, paddingBottom: 120, paddingTop: 8 },
  boardHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: isDark ? '#1e3a8a' : AvColors.blue,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  boardHeroIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boardHeroTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '800',
    color: c.heroText,
    letterSpacing: -0.3,
  },
  card: {
    backgroundColor: AvColors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: AvColors.dividerSoft,
    padding: 16,
    marginBottom: 14,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
      default: {},
    }),
  },
  filtersHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  filtersTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: AvColors.text,
  },
  filtersSub: {
    fontSize: 13,
    color: AvColors.textMuted,
    marginBottom: 14,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  filterField: {
    flex: 1,
    minWidth: 0,
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: AvColors.textMuted,
    marginBottom: 6,
  },
  filterInput: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: AvColors.inputBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AvColors.inputBorder,
    paddingHorizontal: 12,
    paddingVertical: 11,
    minHeight: 44,
  },
  filterInputText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  filterPlaceholder: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: AvColors.inputPlaceholder,
  },
  dropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: 4,
    backgroundColor: AvColors.dropdownBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AvColors.border,
    zIndex: 40,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: AvColors.divider,
  },
  dropdownItemText: {
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  pillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: AvColors.inputBorder,
    backgroundColor: AvColors.chipBg,
  },
  pillActive: {
    backgroundColor: AvColors.chipActiveBg,
    borderColor: AvColors.chipActiveBorder,
  },
  pillText: {
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  pillTextActive: {
    color: AvColors.chipActiveText,
    fontWeight: '700',
  },
  pillDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: AvColors.inputBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AvColors.inputBorder,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: AvColors.text,
    paddingVertical: 10,
  },
  peopleHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  peopleTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: AvColors.text,
  },
  peopleCount: {
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.textMuted,
  },
  personCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AvColors.dividerSoft,
    backgroundColor: AvColors.surfaceElevated,
    marginBottom: 10,
  },
  personMain: {
    flex: 1,
    minWidth: 0,
  },
  personName: {
    fontSize: 16,
    fontWeight: '800',
    color: AvColors.text,
  },
  personRoleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  personRole: {
    fontSize: 12,
    fontWeight: '500',
    color: AvColors.textMuted,
  },
  personGdc: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    color: AvColors.blue,
  },
  personRight: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minWidth: 88,
  },
  statusBadge: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusBadgePresent: {
    backgroundColor: AvColors.greenBg,
  },
  statusBadgeAbsent: {
    backgroundColor: AvColors.orangeBg,
  },
  statusBadgeAway: {
    backgroundColor: isDark ? 'rgba(245,158,11,0.2)' : '#FEF3C7',
  },
  statusBadgeLeave: {
    backgroundColor: AvColors.redBg,
  },
  statusBadgeOffline: {
    backgroundColor: isDark ? 'rgba(148,163,184,0.2)' : '#F1F5F9',
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusBadgeTextPresent: { color: AvColors.greenText },
  statusBadgeTextAbsent: { color: AvColors.orangeText },
  statusBadgeTextAway: { color: isDark ? '#FBBF24' : '#B45309' },
  statusBadgeTextLeave: { color: isDark ? '#fda4af' : AvColors.orangeText },
  statusBadgeTextOffline: { color: isDark ? '#CBD5E1' : '#475569' },
  personHours: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: '600',
    color: AvColors.textMuted,
  },
  dualTabRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  dualTabBtn: {
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  dualTabBtnActive: {
    backgroundColor: isDark ? 'rgba(99,102,241,0.25)' : '#EEF2FF',
  },
  dualTabText: {
    fontSize: 13,
    fontWeight: '700',
    color: AvColors.textMuted,
  },
  dualTabTextActive: {
    color: isDark ? '#A5B4FC' : '#4338CA',
  },
  teamHint: {
    fontSize: 12,
    color: AvColors.textMuted,
    marginBottom: 10,
  },
  boardHeroSub: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.85)',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 14,
  },
  statTile: {
    width: '48%',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.06)',
    minHeight: 88,
    justifyContent: 'space-between',
  },
  statTileWide: {
    width: '100%',
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statTileTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  statTileIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statTileLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: AvColors.textMuted,
  },
  statTileValue: {
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: -0.5,
    color: AvColors.text,
  },
  statTileValueWide: {
    fontSize: 28,
    marginLeft: 12,
  },
  myHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 14,
  },
  myTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: AvColors.text,
    letterSpacing: -0.3,
  },
  mySub: {
    marginTop: 4,
    fontSize: 13,
    color: AvColors.textMuted,
  },
  todayChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: AvColors.card,
    borderWidth: 1,
    borderColor: AvColors.dividerSoft,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  todayChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: AvColors.text,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  bottomKpiRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 8,
  },
  kpiCard: {
    flexGrow: 1,
    flexBasis: '46%',
    minWidth: 140,
    backgroundColor: AvColors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AvColors.dividerSoft,
    padding: 12,
  },
  kpiIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  kpiTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: AvColors.textMuted,
  },
  kpiValue: {
    marginTop: 4,
    fontSize: 20,
    fontWeight: '800',
    color: AvColors.text,
  },
  kpiSub: {
    marginTop: 2,
    fontSize: 11,
    color: AvColors.textMuted,
  },
  scheduleRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  scheduleCard: {
    backgroundColor: AvColors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AvColors.dividerSoft,
    padding: 12,
  },
  scheduleLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: AvColors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  scheduleValue: {
    marginTop: 6,
    fontSize: 15,
    fontWeight: '800',
    color: AvColors.text,
  },
  scheduleMeta: {
    marginTop: 4,
    fontSize: 12,
    color: AvColors.textMuted,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: AvColors.text,
    marginBottom: 12,
  },
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 4,
  },
  weekDay: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 10,
  },
  weekDayToday: {
    backgroundColor: isDark ? 'rgba(99,102,241,0.2)' : '#EEF2FF',
  },
  weekDow: {
    fontSize: 10,
    fontWeight: '700',
    color: AvColors.textMuted,
  },
  weekDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginVertical: 6,
  },
  weekNum: {
    fontSize: 13,
    fontWeight: '800',
    color: AvColors.text,
  },
  logTabRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  logTab: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: AvColors.inputBg,
  },
  logTabActive: {
    backgroundColor: isDark ? 'rgba(99,102,241,0.3)' : '#EEF2FF',
  },
  logTabText: {
    fontSize: 12,
    fontWeight: '700',
    color: AvColors.textMuted,
  },
  logTabTextActive: {
    color: isDark ? '#A5B4FC' : '#4338CA',
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  summaryCard: {
    flexGrow: 1,
    flexBasis: '46%',
    minWidth: 120,
    borderRadius: 12,
    padding: 12,
  },
  summaryPresent: { backgroundColor: isDark ? 'rgba(22,163,74,0.15)' : '#DCFCE7' },
  summaryAbsent: { backgroundColor: isDark ? 'rgba(220,38,38,0.15)' : '#FEE2E2' },
  summaryLeave: { backgroundColor: isDark ? 'rgba(234,88,12,0.15)' : '#FFEDD5' },
  summaryHours: { backgroundColor: isDark ? 'rgba(37,99,235,0.15)' : '#DBEAFE' },
  summaryLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: AvColors.textMuted,
  },
  summaryValue: {
    marginTop: 4,
    fontSize: 20,
    fontWeight: '800',
    color: AvColors.text,
  },
  dateFilterRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  dateSelectField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: AvColors.inputBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AvColors.inputBorder,
    paddingHorizontal: 12,
    paddingVertical: 11,
    minHeight: 44,
  },
  dateSelectText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: AvColors.text,
  },
  logRow: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AvColors.dividerSoft,
    padding: 12,
    marginBottom: 10,
    backgroundColor: AvColors.surfaceElevated,
  },
  logPresent: { borderLeftWidth: 3, borderLeftColor: '#16A34A' },
  logAbsent: { borderLeftWidth: 3, borderLeftColor: '#DC2626' },
  logLeave: { borderLeftWidth: 3, borderLeftColor: '#EA580C' },
  logHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  dateBadge: {
    alignItems: 'center',
    minWidth: 48,
  },
  dateDay: { fontSize: 10, fontWeight: '700', color: AvColors.textMuted },
  dateNumber: { fontSize: 18, fontWeight: '800', color: AvColors.text },
  dateMonth: { fontSize: 10, fontWeight: '700', color: AvColors.textMuted },
  statusBlock: { alignItems: 'flex-end', gap: 4 },
  logStatusPill: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  logStatusPresent: { backgroundColor: AvColors.greenBg },
  logStatusAbsent: { backgroundColor: AvColors.redBg },
  logStatusLeave: { backgroundColor: AvColors.orangeBg },
  logStatusText: { fontSize: 11, fontWeight: '800', color: AvColors.text },
  todayTag: { fontSize: 10, fontWeight: '800', color: '#4F46E5' },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metricPill: {
    flexGrow: 1,
    flexBasis: '22%',
    minWidth: 64,
    borderRadius: 10,
    backgroundColor: AvColors.inputBg,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  hoursPill: {
    backgroundColor: isDark ? 'rgba(37,99,235,0.2)' : '#DBEAFE',
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: AvColors.textMuted,
  },
  metricValue: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '800',
    color: AvColors.text,
  },
  hoursValue: { color: isDark ? '#93C5FD' : '#1D4ED8' },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  activityDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  activityText: {
    fontSize: 11,
    fontWeight: '600',
    color: AvColors.textMuted,
  },
  emptyBox: {
    paddingVertical: 28,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: AvColors.textMuted,
    fontWeight: '500',
  },
  squareAvatar: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: AvColors.avatarBg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  squareAvatarImage: {
    width: 56,
    height: 56,
    borderRadius: 12,
  },
  squareAvatarText: {
    fontSize: 20,
    fontWeight: '800',
    color: AvColors.blue,
  },
  errorBanner: {
    marginBottom: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: AvColors.redBg,
    borderWidth: 1,
    borderColor: AvColors.red,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  errorBannerText: { flex: 1, fontSize: 13, color: AvColors.orangeText, fontWeight: '600' },
  errorBannerBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: AvColors.red,
  },
  errorBannerBtnText: { color: '#fff', fontSize: 12, fontWeight: '800' },
});
}
