import { vars } from 'nativewind';

/** Map app + chat theme tokens to NativeWind CSS variables (exact same colors as before). */
export function buildThemeVars(colors, chatTheme) {
  return vars({
    '--color-page': colors.pageBg,
    '--color-surface': colors.surface,
    '--color-card': colors.card,
    '--color-surface-muted': colors.surfaceMuted,
    '--color-text': colors.text,
    '--color-text-muted': colors.textMuted,
    '--color-text-secondary': colors.textSecondary,
    '--color-border': colors.border,
    '--color-border-light': colors.borderLight,
    '--color-border-strong': colors.borderStrong,
    '--color-input-bg': colors.inputBg,
    '--color-input-underline': colors.inputUnderline,
    '--color-input-placeholder': colors.inputPlaceholder,
    '--color-primary': colors.primary,
    '--color-primary-mid': colors.primaryMid,
    '--color-primary-light': colors.primaryLight,
    '--color-splash-top': colors.splashTop,
    '--color-splash-mid': colors.splashMid,
    '--color-splash-bottom': colors.splashBottom,
    '--color-info-bg': colors.infoBg,
    '--color-info-text': colors.infoText,
    '--color-danger-bg': colors.dangerBg,
    '--color-danger-border': colors.dangerBorder,
    '--color-danger-text': colors.dangerText,
    '--color-skeleton-base': colors.skeletonBase,
    '--color-skeleton-highlight': colors.skeletonHighlight,
    '--chat-wallpaper': chatTheme.wallpaper,
    '--chat-bubble-out': chatTheme.bubbleOut,
    '--chat-bubble-in': chatTheme.bubbleIn,
    '--chat-bubble-out-text': chatTheme.bubbleOutText,
    '--chat-bubble-in-text': chatTheme.bubbleInText,
    '--chat-meta-muted': chatTheme.metaMuted,
    '--chat-chrome-bg': chatTheme.chromeBg,
    '--chat-header-border': chatTheme.headerBorder,
    '--chat-composer-bar': chatTheme.composerBar,
    '--chat-input-bg': chatTheme.inputBg,
    '--chat-send-btn': chatTheme.sendBtn,
    '--chat-send-btn-disabled': chatTheme.sendBtnDisabled,
    '--chat-date-pill-bg': chatTheme.datePillBg,
    '--chat-date-pill-text': chatTheme.datePillText,
    '--chat-role-badge-bg': chatTheme.roleBadgeBg,
    '--chat-role-badge-text': chatTheme.roleBadgeText,
    '--chat-reply-bg': chatTheme.replyBg,
    '--chat-reply-bar': chatTheme.replyBar,
    '--chat-reply-composer-bg': chatTheme.replyComposerBg,
    '--chat-reply-composer-border': chatTheme.replyComposerBorder,
    '--chat-msg-time-out': chatTheme.msgTimeOut,
    '--chat-group-sender': chatTheme.groupSenderName,
  });
}
